# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-01 18:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clicks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_of_click', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-time_of_click'],
            },
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('short_version', models.CharField(max_length=30)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-added'],
            },
        ),
        migrations.AddField(
            model_name='clicks',
            name='referenced_url',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shorten_app.Url'),
        ),
    ]
